@startuml SimpleRemoteInitializationSequence

title Simple Remote Initialisation sequence

actor User
participant VSCode
participant Broker as "Remote broker"
database Database1
database Database2

User -> Broker ++ #Azure : Start
Broker ->  Broker : CREATE Broker-SOCKET
User <-- Broker : Started
User -> VSCode ++ #Gold : Start
VSCode ->  VSCode : GetAvailablePort\n(port)
VSCode -[#green]> Broker : GetStatus
VSCode <[#green]-- Broker : Status\n(Running)
VSCode -[#green]>  Broker : GetDbNameList
Broker -[#green]>  Broker : GetDbNameListFromConfig\n(db1, db2, etc.)
VSCode <[#green]-- Broker : DbNameList\n(db1, db2, etc.)
VSCode -[#green]>  Broker : GetDbVersion\n(name)

activate Broker #Azure
Broker -[#green]>  Broker : GetConnParamsConfig\n(host, port, etc.)
Broker -> Database1 : CONNECT VALUE (host, port, etc.)
Broker <-- Database1
Broker -> Database1 : DBVERSION
Broker <-- Database1
VSCode <-- Broker : DbVersion\n(version)
deactivate Broker

VSCode -[#green]>  Broker : GetDbVersion\n(name)

activate Broker #Azure
Broker -[#green]>  Broker : GetConnParamsConfig\n(host, port, etc.)
Broker -> Database2 : CONNECT VALUE (host, port, etc.)
Broker <-- Database2
Broker -> Database2 : DBVERSION
Broker <-- Database2
VSCode <-- Broker : DbVersion\n(version)
deactivate Broker
User <-- VSCode : End
User <-- Broker : End

@enduml