@startuml SimpleRemoteInitializationSequence

title Simple Remote Initialisation sequence

actor User
participant VSCode
participant Server as "Remote Server"
database Database1
database Database2

User -> Server ++ #Azure : Start
Server ->  Server : CREATE SERVER-SOCKET
User <-- Server : Started
User -> VSCode ++ #Gold : Start
VSCode ->  VSCode : GetAvailablePort\n(port)
VSCode -[#green]> Server : GetStatus
VSCode <[#green]-- Server : Status\n(Running)
VSCode -[#green]>  Server : GetDbNameList
Server -[#green]>  Server : GetDbNameListFromConfig\n(db1, db2, etc.)
VSCode <[#green]-- Server : DbNameList\n(db1, db2, etc.)
VSCode -[#green]>  Server : GetDbVersion\n(name)

activate Server #Azure
Server -[#green]>  Server : GetConnParamsConfig\n(host, port, etc.)
Server -> Database1 : CONNECT VALUE (host, port, etc.)
Server <-- Database1
Server -> Database1 : DBVERSION
Server <-- Database1
VSCode <-- Server : DbVersion\n(version)
deactivate Server

VSCode -[#green]>  Server : GetDbVersion\n(name)

activate Server #Azure
Server -[#green]>  Server : GetConnParamsConfig\n(host, port, etc.)
Server -> Database2 : CONNECT VALUE (host, port, etc.)
Server <-- Database2
Server -> Database2 : DBVERSION
Server <-- Database2
VSCode <-- Server : DbVersion\n(version)
deactivate Server
User <-- VSCode : End
User <-- Server : End

@enduml