export enum OEDataTypePrimitive {
    Blob = 'BLOB',
    Character = 'CHARACTER',
    Clob = 'CLOB',
    ComHandle = 'COM-HANDLE',
    Date = 'DATE',
    Datetime = 'DATETIME',
    DatetimeTz = 'DATETIME-TZ',
    Decimal = 'DECIMAL',
    Handle = 'HANDLE',
    Int64 = 'INT64',
    Integer = 'INTEGER',
    Logical = 'LOGICAL',
    Longchar = 'LONGCHAR',
    Memptr = 'MEMPTR',
    Raw = 'RAW',
    Recid = 'RECID',
    Rowid = 'ROWID',
    WidgetHandle = 'WIDGET-HANDLE',
}
