version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Compile Extension
          command: npm run compile:extension
      - run:
          name: Compile Views
          command: npm run compile:views
  compile:
    docker:
      - image: kherring/oedb:latest
    steps:
      - checkout
      - run: tr ' ' '\n' \<<< "$PROGRESS_CFG_BASE64" | base64 --decode > /psc/dlc/progress.cfg        
workflows:
  build:
    jobs:
      - build
      - compile