version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
      working_directory: ./src
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Compile Extension
          command: npm run compile:extension
      - run:
          name: Compile Views
          command: npm run compile:views
workflows:
  build:
    jobs:
      - build