version: '3.7'
services:
  sports-db-128:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
      args:
        - IMAGE_NAME=${IMAGE_NAME_128}
        - DB_NAME=${DB_NAME}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_MIN_PORT=${DB_MIN_PORT}
      - DB_MAX_PORT=${DB_MAX_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
      - ${DB_MIN_PORT}-${DB_MAX_PORT}:${DB_MIN_PORT}-${DB_MAX_PORT}
  sports-db-128-2:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
      args:
        - IMAGE_NAME=${IMAGE_NAME_128}
        - DB_NAME=${DB_NAME2}
    environment:
      - DB_NAME=${DB_NAME2}
      - DB_PORT=${DB_PORT2}
      - DB_MIN_PORT=${DB_MIN_PORT2}
      - DB_MAX_PORT=${DB_MAX_PORT2}
    ports:
      - ${DB_PORT2}:${DB_PORT2}
      - ${DB_MIN_PORT2}-${DB_MAX_PORT2}:${DB_MIN_PORT2}-${DB_MAX_PORT2}
